name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      run: |
        cd web
        npm install

    - name: Build
      run: |
        cd web
        npm run build

    - name: Move build files
      run: |
        rm -rf web/build
        mv web/dist web/build

    - name: Create Release Artifact
      if: github.event_name == 'release'
      run: |
        zip -r zUI.zip ./* \
          -x "web/node_modules/*" \
          -x "web/src/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x "web/package.json" \
          -x "web/package-lock.json" \
          -x "web/vite.config.js" \
          -x "web/.gitignore"

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./zUI.zip
        asset_name: zUI.zip
        asset_content_type: application/zip

    - name: Commit and push build files
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add web/build
        git commit -m "chore: update build files [skip ci]" || echo "No changes to commit"
        git push